name: "Test"

on:
  pull_request:
  push:

jobs:
  ghc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A ghc

  ghc884:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A ghc884

  ghc8107:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A ghc8107

  ghc902:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A ghc902

  ghc925:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A ghc925

  stack-aeson-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: haskell/actions/setup@v1
      - uses: actions/cache@v2.1.6
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: linux-stack-nightly-aeson2
      - name: Test
        run: stack test

  ghcjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: cachix use miso-haskell
      - run: nix-build -A ghcjs
