name: "Test"

on:
  pull_request:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
  ghc:
    needs: setup
    steps:
      - nix-build -A ghc
  ghcjs:
    needs: setup
    steps:
      - nix-env -iA nixpkgs.cachix
      - cachix use miso-haskell
      - nix-build -A ghcjs
