name: "Test"

on:
  pull_request:
  push:

jobs:
  ghc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A ghc

  ghc884:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A ghc884

  ghc8107:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A ghc8107

  ghc902:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A ghc902

  ghc921:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A ghc921

  stack-aeson-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-shell -p stack --run "stack test"

  ghcjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: aeson-combinators
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: cachix use miso-haskell
      - run: nix-build -A ghcjs
